server:
  port: 8080

spring:
  application:
    name: documentscreated
---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: documentscreated
#<<< EDA / Topic Name
          destination: aivlebigproject
#>>> EDA / Topic Name
          contentType: application/json
        event-out:
#<<< EDA / Topic Name
          destination: aivlebigproject
#>>> EDA / Topic Name
          contentType: application/json
        event-out-funeral-request:  # FastAPI 쪽으로 요청
          destination: funeral-request
          contentType: application/json

        event-in-document-response:  # FastAPI로부터 생성 결과 받을 곳
          group: documentscreated
          destination: funeral-response
          contentType: application/json
        outboundSamangAiRequest: # <-- Samang AI용 바인딩 추가
          destination: samang-ai-request-topic # Samang AI가 구독할 토픽 이름 (새로 정의)
        outboundTimetableAiRequest: # <-- Timetable AI용 바인딩 추가
          destination: timetable-ai-request-topic # Timetable AI가 구독할 토픽 이름 (새로 정의)

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

api:
  url: 
    documentscreated: localhost:8083 
    

server:
  port: 8083

---

spring:
  profiles: docker
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: documentscreated
          destination: aivlebigproject
          contentType: application/json
        event-out:
          destination: aivlebigproject
          contentType: application/json
        event-out-funeral-request:  # FastAPI 쪽으로 요청
          destination: funeral-request
          contentType: application/json

        event-in-document-response:  # FastAPI로부터 생성 결과 받을 곳
          group: documentscreated
          destination: funeral-response
          contentType: application/json

api:
  url: 
    documentscreated: documentscreated:8080 
    

