apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentscreated
  labels:
    app: documentscreated
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documentscreated
  template:
    metadata:
      labels:
        app: documentscreated
    spec:
      containers:
        - name: documentscreated
          image: "username/documentscreated:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
