server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: login
          uri: http://localhost:8082
          predicates:
            - Path=/users/**, /customerProfiles/**, 
        - id: documentscreated
          uri: http://localhost:8083
          predicates:
            - Path=/funeralInfos/**, /documentSaves/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: login
          uri: http://login:8080
          predicates:
            - Path=/users/**, /customerProfiles/**, 
        - id: documentscreated
          uri: http://documentscreated:8080
          predicates:
            - Path=/funeralInfos/**, /documentSaves/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
